namespace SmartPacking.Infrastructure;

public sealed class UserEntity { public Guid Id { get; set; } public string Name { get; set; } = string.Empty; public string? ExternalIssuer { get; set; } public string? ExternalSubject { get; set; } public bool IsOnboarded { get; set; } public string? Address { get; set; } public string? Street { get; set; } public string? PostalCode { get; set; } public string? City { get; set; } public string? Region { get; set; } public string AiPlan { get; set; } = "Free"; public int AiRecognitionCredits { get; set; } }
public sealed class UserAuditEventEntity { public Guid Id { get; set; } public Guid UserId { get; set; } public DateTimeOffset OccurredAt { get; set; } public string Action { get; set; } = string.Empty; }
public sealed class GarmentRecognitionEventEntity { public Guid Id { get; set; } public Guid UserId { get; set; } public DateTimeOffset OccurredAt { get; set; } }
public sealed class ClothingItemEntity { public Guid Id { get; set; } public Guid UserId { get; set; } public string Name { get; set; } = string.Empty; public int Type { get; set; } public int Season { get; set; } public string Color { get; set; } = string.Empty; public int WarmthLevel { get; set; } public bool Waterproof { get; set; } public int Style { get; set; } public int? WeightGrams { get; set; } public bool IsClean { get; set; } public bool IsAvailable { get; set; } public int PreferenceScore { get; set; } public bool IsDeleted { get; set; } public Guid? OwnerProfileId { get; set; } public string? PhotoUrl { get; set; } public string? Material { get; set; } public string CombinationIds { get; set; } = "[]"; }
public sealed class TripEntity { public Guid Id { get; set; } public Guid UserId { get; set; } public string Destination { get; set; } = string.Empty; public DateOnly StartDate { get; set; } public DateOnly EndDate { get; set; } public int MinimumTemperatureCelsius { get; set; } public int MaximumTemperatureCelsius { get; set; } public string Activities { get; set; } = "[]"; public string? TemplateKey { get; set; } public int LuggageAllowanceGrams { get; set; } = 10000; public bool CabinOnly { get; set; } = true; public int LuggageType { get; set; } public int LuggageHeightCentimetres { get; set; } = 55; public int LuggageWidthCentimetres { get; set; } = 40; public int LuggageDepthCentimetres { get; set; } = 20; public string DayPlans { get; set; } = "[]"; public string? AirlineCode { get; set; } public string TransportTypes { get; set; } = "[]"; public string Luggages { get; set; } = "[]"; public string? Origin { get; set; } public string? TransportPlan { get; set; } }
public sealed class PackingListEntity { public Guid Id { get; set; } public Guid TripId { get; set; } public Guid UserId { get; set; } public DateTimeOffset CreatedAt { get; set; } }
public sealed class PackingListItemEntity { public Guid PackingListId { get; set; } public Guid ClothingItemId { get; set; } public bool IsPacked { get; set; } }
public sealed class ChecklistItemEntity { public Guid Id { get; set; } public Guid UserId { get; set; } public Guid TripId { get; set; } public Guid? ProfileId { get; set; } public int Category { get; set; } public string Name { get; set; } = string.Empty; public bool IsPacked { get; set; } }
public sealed class ClothingUsageEntity { public Guid TripId { get; set; } public Guid ClothingItemId { get; set; } public Guid UserId { get; set; } public bool WasUsed { get; set; } }
public sealed class FamilyProfileEntity { public Guid Id { get; set; } public Guid UserId { get; set; } public string Name { get; set; } = string.Empty; public bool IsArchived { get; set; } public string? PackingNotes { get; set; } public string? MedicalNotes { get; set; } }
public sealed class TripProfileEntity { public Guid TripId { get; set; } public Guid ProfileId { get; set; } public Guid UserId { get; set; } }
public sealed class ProfilePackingListEntity { public Guid Id { get; set; } public Guid TripId { get; set; } public Guid ProfileId { get; set; } public Guid UserId { get; set; } public DateTimeOffset CreatedAt { get; set; } }
public sealed class ProfilePackingListItemEntity { public Guid PackingListId { get; set; } public Guid ClothingItemId { get; set; } public bool IsPacked { get; set; } }
public sealed class UserTripTemplateEntity { public Guid Id { get; set; } public Guid UserId { get; set; } public string Name { get; set; } = string.Empty; public string Description { get; set; } = string.Empty; public string Activities { get; set; } = "[]"; public int MinimumTemperatureCelsius { get; set; } public int MaximumTemperatureCelsius { get; set; } public int LuggageAllowanceGrams { get; set; } public bool CabinOnly { get; set; } }
