using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SmartPacking.Infrastructure;

public sealed class UserConfiguration : IEntityTypeConfiguration<UserEntity> { public void Configure(EntityTypeBuilder<UserEntity> builder) { builder.HasKey(entity => entity.Id); builder.HasIndex(entity => new { entity.ExternalIssuer, entity.ExternalSubject }).IsUnique(); } }
public sealed class UserAuditEventConfiguration : IEntityTypeConfiguration<UserAuditEventEntity> { public void Configure(EntityTypeBuilder<UserAuditEventEntity> builder) { builder.HasKey(entity => entity.Id); builder.Property(entity => entity.OccurredAt).HasConversion(value => value.ToUnixTimeMilliseconds(), value => DateTimeOffset.FromUnixTimeMilliseconds(value)); builder.HasIndex(entity => new { entity.UserId, entity.OccurredAt }); } }
public sealed class GarmentRecognitionEventConfiguration : IEntityTypeConfiguration<GarmentRecognitionEventEntity> { public void Configure(EntityTypeBuilder<GarmentRecognitionEventEntity> builder) { builder.HasKey(entity => entity.Id); builder.Property(entity => entity.OccurredAt).HasConversion(value => value.ToUnixTimeMilliseconds(), value => DateTimeOffset.FromUnixTimeMilliseconds(value)); builder.HasIndex(entity => new { entity.UserId, entity.OccurredAt }); } }
public sealed class ClothingItemConfiguration : IEntityTypeConfiguration<ClothingItemEntity> { public void Configure(EntityTypeBuilder<ClothingItemEntity> builder) { builder.HasKey(entity => entity.Id); builder.HasIndex(entity => new { entity.UserId, entity.Name }).IsUnique(); builder.HasIndex(entity => new { entity.UserId, entity.IsDeleted }); builder.HasIndex(entity => new { entity.UserId, entity.OwnerProfileId }); } }
public sealed class TripConfiguration : IEntityTypeConfiguration<TripEntity> { public void Configure(EntityTypeBuilder<TripEntity> builder) { builder.HasKey(entity => entity.Id); builder.HasIndex(entity => new { entity.UserId, entity.StartDate }); } }
public sealed class PackingListConfiguration : IEntityTypeConfiguration<PackingListEntity> { public void Configure(EntityTypeBuilder<PackingListEntity> builder) { builder.HasKey(entity => entity.Id); builder.HasIndex(entity => new { entity.UserId, entity.TripId }).IsUnique(); } }
public sealed class PackingListItemConfiguration : IEntityTypeConfiguration<PackingListItemEntity> { public void Configure(EntityTypeBuilder<PackingListItemEntity> builder) => builder.HasKey(entity => new { entity.PackingListId, entity.ClothingItemId }); }
public sealed class ChecklistItemConfiguration : IEntityTypeConfiguration<ChecklistItemEntity> { public void Configure(EntityTypeBuilder<ChecklistItemEntity> builder) { builder.HasKey(entity => entity.Id); builder.HasIndex(entity => new { entity.UserId, entity.TripId }); } }
public sealed class ClothingUsageConfiguration : IEntityTypeConfiguration<ClothingUsageEntity> { public void Configure(EntityTypeBuilder<ClothingUsageEntity> builder) => builder.HasKey(entity => new { entity.TripId, entity.ClothingItemId }); }
public sealed class FamilyProfileConfiguration : IEntityTypeConfiguration<FamilyProfileEntity> { public void Configure(EntityTypeBuilder<FamilyProfileEntity> builder) { builder.HasKey(entity => entity.Id); builder.HasIndex(entity => new { entity.UserId, entity.Name }).IsUnique(); builder.HasIndex(entity => new { entity.UserId, entity.IsArchived }); } }
public sealed class TripProfileConfiguration : IEntityTypeConfiguration<TripProfileEntity> { public void Configure(EntityTypeBuilder<TripProfileEntity> builder) { builder.HasKey(entity => new { entity.TripId, entity.ProfileId }); builder.HasIndex(entity => new { entity.UserId, entity.TripId }); } }
public sealed class ProfilePackingListConfiguration : IEntityTypeConfiguration<ProfilePackingListEntity> { public void Configure(EntityTypeBuilder<ProfilePackingListEntity> builder) { builder.HasKey(entity => entity.Id); builder.HasIndex(entity => new { entity.UserId, entity.TripId, entity.ProfileId }).IsUnique(); } }
public sealed class ProfilePackingListItemConfiguration : IEntityTypeConfiguration<ProfilePackingListItemEntity> { public void Configure(EntityTypeBuilder<ProfilePackingListItemEntity> builder) => builder.HasKey(entity => new { entity.PackingListId, entity.ClothingItemId }); }
public sealed class UserTripTemplateConfiguration : IEntityTypeConfiguration<UserTripTemplateEntity> { public void Configure(EntityTypeBuilder<UserTripTemplateEntity> builder) { builder.HasKey(entity => entity.Id); builder.HasIndex(entity => new { entity.UserId, entity.Name }).IsUnique(); } }
